[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit INA219 @ ^1.2.3

[env:target]
build_src_filter = +<target.cpp> -<observer.cpp>
build_flags = -D NODE_TARGET

[env:observer]
build_src_filter = +<observer.cpp> -<target.cpp>
build_flags = -D NODE_OBSERVER