[platformio]
default_envs = target

[env:target]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp> +<bonus.cpp> -<monitor.cpp>

lib_deps = 
    kosme/arduinoFFT @ ^2.0.4
    knolleary/PubSubClient @ ^2.8.0
    jgromes/RadioLib @ ^6.6.0

[env:monitor]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
build_src_filter = +<monitor.cpp> -<main.cpp> -<bonus.cpp>

lib_deps = 
    adafruit/Adafruit INA219 @ ^1.2.3